FROM eclipse-temurin:21-alpine
LABEL author=shaikkhajaibrahim
LABEL project=learning
LABEL version=3.3.0
EXPOSE 8080
RUN wget https://referenceappslt.s3.ap-south-1.amazonaws.com/spring-petclinic-3.3.0-SNAPSHOT.jar
CMD ["java", "-jar", "spring-petclinic-3.3.0-SNAPSHOT.jar"]

